logging:
  level:
    org:
      springframework:
        data:
          neo4j: ERROR

spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  datasource:
    # Postgres database
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:24889/gingermill
    username: gingermill
    password: gingermill
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    contexts: default
    database-change-log-table: ta_databasechangelog
    database-change-log-lock-table: ta_databasechangeloglock
  data:
    neo4j:
      database: neo4j
  application:
    name: gingermill
  neo4j:
    uri: bolt://localhost
    authentication:
      username: neo4j
      password: pass
server:
  port: 8081

