
spring:
  data:
    neo4j:
      database: neo4j
  application:
    name: gingermill
  neo4j:
    uri: bolt://localhost
    authentication:
      username: neo4j
      password: pass
server:
  port: 8081
